apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-deploy
spec:
  selector:
    matchLabels:
      app: k8s-web-hello-deploy
  replicas: 4
  template:
    metadata:
      labels:
        app: k8s-web-hello-deploy
    spec:
      containers:
      - name: k8s-web-hello-deploy
        image: budhajit15/k8s-web-hello:2.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
