apiVersion: v1
kind: Service
metadata:
  name: k8s-web-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-nginx
  ports:
  - port: 3333
    targetPort: 3000

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-nginx
spec:
  selector:
    matchLabels:
      app: k8s-web-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-web-nginx
    spec:
      containers:
      - name: k8s-web-nginx
        image: budhajit15/k8s-web-hello-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000